// ui/src/app/features/dashboard/dashboard.component.ts
import { Component, ChangeDetectionStrategy, inject, signal, computed, DestroyRef } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { interval, EMPTY } from 'rxjs';
import { startWith, switchMap, catchError } from 'rxjs/operators';
import { OrderService } from '../../core/services/order.service';
import { InventoryService } from '../../core/services/inventory.service';
import { DeliveryService } from '../../core/services/delivery.service';
import { StatusBadgeComponent } from '../../shared/components/status-badge/status-badge.component';
import { ErrorBannerComponent } from '../../shared/components/error-banner/error-banner.component';
import { Order, InventoryItem, Delivery } from '../../shared/models/types';

@Component({
  selector: 'app-dashboard',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [StatusBadgeComponent, ErrorBannerComponent],
  template: `
    <div>
      <h1 class="text-2xl font-bold text-base-content mb-6">Dashboard</h1>

      <app-error-banner [error]="ordersError()" title="Could not load orders" />
      <app-error-banner [error]="inventoryError()" title="Could not load inventory" />
      <app-error-banner [error]="deliveriesError()" title="Could not load deliveries" />

      <!-- Stat cards -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <div class="card bg-base-200 border border-base-300">
          <div class="card-body p-5">
            <p class="text-sm text-base-content/60">Total Orders</p>
            <p class="text-3xl font-bold mt-1">{{ orders().length || '—' }}</p>
            <p class="text-xs text-base-content/40 mt-1">
              P:{{ statusCount('PENDING') }} C:{{ statusCount('CONFIRMED') }} X:{{ statusCount('CANCELLED') }}
            </p>
          </div>
        </div>
        <div class="card bg-base-200 border border-base-300">
          <div class="card-body p-5">
            <p class="text-sm text-base-content/60">Inventory Items</p>
            <p class="text-3xl font-bold mt-1">{{ inventory().length || '—' }}</p>
            <p class="text-xs text-base-content/40 mt-1">{{ totalAvailable() }} units available</p>
          </div>
        </div>
        <div class="card bg-base-200 border border-base-300">
          <div class="card-body p-5">
            <p class="text-sm text-base-content/60">Active Deliveries</p>
            <p class="text-3xl font-bold mt-1">{{ scheduledCount() }}</p>
            <p class="text-xs text-base-content/40 mt-1">SCHEDULED status</p>
          </div>
        </div>
        <div class="card bg-base-200 border border-base-300">
          <div class="card-body p-5">
            <p class="text-sm text-base-content/60">Confirmed Orders</p>
            <p class="text-3xl font-bold mt-1">{{ statusCount('CONFIRMED') }}</p>
            <p class="text-xs text-base-content/40 mt-1">Successfully fulfilled</p>
          </div>
        </div>
      </div>

      <!-- Recent orders table -->
      <div class="card bg-base-200 border border-base-300">
        <div class="card-body p-0">
          <div class="px-5 py-4 border-b border-base-300">
            <h2 class="text-base font-semibold">Recent Orders</h2>
            <p class="text-xs text-base-content/40 mt-0.5">Auto-refreshes every 5s</p>
          </div>
          <div class="overflow-x-auto">
            <table class="table table-zebra w-full">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Product</th>
                  <th>Qty</th>
                  <th>Status</th>
                  <th>Created</th>
                </tr>
              </thead>
              <tbody>
                @if (ordersLoading()) {
                  <tr>
                    <td colspan="5" class="text-center py-8 text-base-content/60">
                      <span class="loading loading-spinner loading-sm"></span>
                      Loading…
                    </td>
                  </tr>
                } @else if (recentOrders().length === 0) {
                  <tr>
                    <td colspan="5" class="text-center py-8 text-base-content/60">No orders yet</td>
                  </tr>
                } @else {
                  @for (order of recentOrders(); track order.id) {
                    <tr>
                      <td class="font-mono text-xs">{{ order.id }}</td>
                      <td>{{ order.productId }}</td>
                      <td>{{ order.quantity }}</td>
                      <td><app-status-badge [status]="order.status" /></td>
                      <td class="text-xs text-base-content/60">{{ formatDate(order.createdAt) }}</td>
                    </tr>
                  }
                }
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class DashboardComponent {
  private orderService = inject(OrderService);
  private inventoryService = inject(InventoryService);
  private deliveryService = inject(DeliveryService);
  private destroyRef = inject(DestroyRef);

  orders = signal<Order[]>([]);
  inventory = signal<InventoryItem[]>([]);
  deliveries = signal<Delivery[]>([]);
  ordersLoading = signal(true);
  ordersError = signal<unknown>(null);
  inventoryError = signal<unknown>(null);
  deliveriesError = signal<unknown>(null);

  recentOrders = computed(() =>
    [...this.orders()]
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, 5)
  );

  totalAvailable = computed(() =>
    this.inventory().reduce(
      (acc, i) => acc + (i.availableQuantity ?? (i.quantity - (i.reservedQuantity ?? 0))),
      0
    )
  );

  scheduledCount = computed(() => this.deliveries().filter(d => d.status === 'SCHEDULED').length);

  statusCount(status: string): number {
    return this.orders().filter(o => o.status === status).length;
  }

  constructor() {
    interval(5000).pipe(
      startWith(0),
      switchMap(() =>
        this.orderService.getOrders().pipe(
          catchError(err => { this.ordersError.set(err); return EMPTY; })
        )
      ),
      takeUntilDestroyed(this.destroyRef),
    ).subscribe(data => {
      this.orders.set(data);
      this.ordersLoading.set(false);
      this.ordersError.set(null);
    });

    this.inventoryService.getInventory()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: data => this.inventory.set(data),
        error: err => this.inventoryError.set(err),
      });

    interval(5000).pipe(
      startWith(0),
      switchMap(() =>
        this.deliveryService.getDeliveries().pipe(
          catchError(err => { this.deliveriesError.set(err); return EMPTY; })
        )
      ),
      takeUntilDestroyed(this.destroyRef),
    ).subscribe(data => {
      this.deliveries.set(data);
      this.deliveriesError.set(null);
    });
  }

  formatDate(ts: string | undefined): string {
    if (!ts) return '—';
    return new Date(ts).toLocaleString();
  }
}

// ui/src/features/dashboard/Dashboard.tsx
import { useGetOrdersQuery, useGetInventoryQuery, useGetDeliveriesQuery } from '../../services/api'
import StatusBadge from '../../components/StatusBadge'
import ErrorBanner from '../../components/ErrorBanner'
import type { OrderStatus } from '../../types'

interface StatCardProps {
  label: string
  value: number | undefined
  sub?: string
}

function StatCard({ label, value, sub }: StatCardProps) {
  return (
    <div className="bg-slate-800 rounded-xl p-5 border border-slate-700">
      <p className="text-sm text-slate-400">{label}</p>
      <p className="mt-1 text-3xl font-bold text-white">{value ?? '—'}</p>
      {sub && <p className="mt-1 text-xs text-slate-500">{sub}</p>}
    </div>
  )
}

function formatDate(ts: string | undefined) {
  if (!ts) return '—'
  return new Date(ts).toLocaleString()
}

export default function Dashboard() {
  const { data: orders, error: ordersError, isLoading: ordersLoading } = useGetOrdersQuery(undefined, {
    pollingInterval: 5000,
  })
  const { data: inventory, error: inventoryError } = useGetInventoryQuery()
  const { data: deliveries, error: deliveriesError } = useGetDeliveriesQuery(undefined, {
    pollingInterval: 5000,
  })

  const ordersByStatus = (orders ?? []).reduce<Record<string, number>>((acc, o) => {
    acc[o.status] = (acc[o.status] ?? 0) + 1
    return acc
  }, {})

  const totalAvailable = (inventory ?? []).reduce((acc, i) => acc + (i.availableQuantity ?? i.quantity - (i.reservedQuantity ?? 0)), 0)
  const scheduledCount = (deliveries ?? []).filter((d) => d.status === 'SCHEDULED').length
  const recentOrders = [...(orders ?? [])].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).slice(0, 5)

  return (
    <div>
      <h1 className="text-2xl font-bold text-white mb-6">Dashboard</h1>

      <ErrorBanner error={ordersError} title="Could not load orders" />
      <ErrorBanner error={inventoryError} title="Could not load inventory" />
      <ErrorBanner error={deliveriesError} title="Could not load deliveries" />

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <StatCard
          label="Total Orders"
          value={orders?.length}
          sub={ordersLoading ? 'Loading…' : `P:${ordersByStatus['PENDING'] ?? 0} C:${ordersByStatus['CONFIRMED'] ?? 0} X:${ordersByStatus['CANCELLED'] ?? 0}`}
        />
        <StatCard
          label="Inventory Items"
          value={inventory?.length}
          sub={`${totalAvailable} units available`}
        />
        <StatCard
          label="Active Deliveries"
          value={scheduledCount}
          sub="SCHEDULED status"
        />
        <StatCard
          label="Confirmed Orders"
          value={ordersByStatus['CONFIRMED'] ?? 0}
          sub="Successfully fulfilled"
        />
      </div>

      <div className="bg-slate-800 rounded-xl border border-slate-700">
        <div className="px-5 py-4 border-b border-slate-700">
          <h2 className="text-base font-semibold text-white">Recent Orders</h2>
          <p className="text-xs text-slate-500 mt-0.5">Auto-refreshes every 5s</p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-slate-400 border-b border-slate-700">
                <th className="px-5 py-3 font-medium">ID</th>
                <th className="px-5 py-3 font-medium">Product</th>
                <th className="px-5 py-3 font-medium">Qty</th>
                <th className="px-5 py-3 font-medium">Status</th>
                <th className="px-5 py-3 font-medium">Created</th>
              </tr>
            </thead>
            <tbody>
              {recentOrders.length === 0 && (
                <tr>
                  <td colSpan={5} className="px-5 py-8 text-center text-slate-500">
                    {ordersLoading ? 'Loading…' : 'No orders yet'}
                  </td>
                </tr>
              )}
              {recentOrders.map((order) => (
                <tr key={order.id} className="border-b border-slate-700/50 hover:bg-slate-700/30 transition-colors">
                  <td className="px-5 py-3 text-slate-300 font-mono text-xs">{order.id}</td>
                  <td className="px-5 py-3 text-slate-200">{order.productId}</td>
                  <td className="px-5 py-3 text-slate-200">{order.quantity}</td>
                  <td className="px-5 py-3"><StatusBadge status={order.status as OrderStatus} /></td>
                  <td className="px-5 py-3 text-slate-400 text-xs">{formatDate(order.createdAt)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
